#!/usr/bin/env bash

# Copyright 2016 Cisco Systems, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script should *only* be called when `lc` is not available.
# The script will create `lc` binaries in the `./target/` directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
export COMPOSE_PROJECT_NAME=elsy
set -e

command -v docker >/dev/null 2>&1 || {
  echo "did not find docker" >&2
  echo "docker required for proper operation" >&2
  exit 1
}

command -v docker-compose >/dev/null 2>&1 || {
  echo "did not find docker-compose" >&2
  echo "docker-compose required for proper operation" >&2
  exit 1
}

docker pull golang:latest
docker-compose run --rm installdependencies
docker-compose build
docker-compose run --rm package
