#!/bin/bash

# Copyright 2016 Cisco Systems, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

: ${DB_PORT:=3306}

wait_for_services(){
  if [ -z "$DB_HOST" ]; then
    echo "DB_HOST required" >&2
    exit 1
  fi
  wait_for_endpoint "$DB_HOST" "$DB_PORT"
}

wait_for_endpoint() {
  printf "Waiting for: $1\n"
  until $(nc -z -w1 $1 $2); do
    printf '.'
    sleep 1
  done
  printf "\n"
}

verify_db(){
  java -jar java-note-service.jar db status config.yml 2>/dev/null | grep 'up to date' > /dev/null 2>&1
}

## will wait until the db is ready for work
wait_for_db_migration(){
  printf "Waiting for db migrations to be applied\n"
  until $(verify_db); do
    printf '.'
    sleep 1
  done
  printf "\n"
}
