#!/usr/bin/env bash

# Copyright 2016 Cisco Systems, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

## remove previous job's artifacts
rm -f ./target/lc*

arch=amd64
platforms=(darwin linux)
build=`git rev-parse HEAD`
version="snapshot-$build"

## the authoritative regex for release tags is in ./helpers/git.go
if [ -n "$GIT_TAG_NAME" ] && [[ "$GIT_TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
  version="$GIT_TAG_NAME"
  echo "packaging release binary using version '$version'"
else
  echo "packaging snapshot binary using version '$version'"
fi

for platform in "${platforms[@]}"; do
  GOOS=${platform} GOARCH=${arch} go build -v -o target/lc-${platform}-${arch}-${version} \
    --ldflags "-X github.com/cisco/elsy/helpers.version=$version \
    -X github.com/cisco/elsy/helpers.build=$build" \
    ./main
done

## create a binary for blackbox tests to use
cp target/lc-linux-${arch}-${version} target/lc-blackbox
