#!/usr/bin/env bash

# Copyright 2016 Cisco Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

files=$(gofmt -l ./command ./helpers ./main ./template)
if [ -n "$files" ] ; then
  echo "the following files are not formatted according to the gofmt rules;" >&2
  echo $files >&2
  exit 1
fi

echo go test ./command ./helpers ./main ./template
go test ./command ./helpers ./main ./template

echo go vet ./command ./helpers ./main ./template
go vet ./command ./helpers ./main ./template
