#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/pre-req-check

set -e
unbuffer ${DIR}/bootstrap
unbuffer ${DIR}/test
unbuffer ${DIR}/package
unbuffer ${DIR}/smoketest
unbuffer ${DIR}/publish
