#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/pre-req-check

set -e
cd $DIR/../

arch=amd64
platforms=(darwin linux)
for platform in "${platforms[@]}"; do
  docker-compose run --rm -e GOOS=${platform} -e GOARCH=${arch} go build -v -o target/lc-${platform}-${arch} ./main
done
