#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export COMPOSE_PROJECT_NAME=projectlifecycle

command -v docker >/dev/null 2>&1 || {
  echo "did not find docker" >&2
  echo "install local-docker-stack https://stash0.eng.lancope.local/projects/DEV-INFRASTRUCTURE/repos/local-docker-stack/browse" >&2
  exit 1
}

command -v docker-compose >/dev/null 2>&1 || {
  echo "did not find docker-compose" >&2
  echo "install local-docker-stack https://stash0.eng.lancope.local/projects/DEV-INFRASTRUCTURE/repos/local-docker-stack/browse" >&2
  exit 1
}
