#!/usr/bin/env bash
set -e

## remove previous job's artifacts
rm -f ./target/lc*

arch=amd64
platforms=(darwin linux)
version=`cat ./VERSION`
build=`git rev-parse HEAD`

## the authoritative regex for release tags is in ./command/publish.go
if [ -n "$GIT_TAG_NAME" ] && [[ "$GIT_TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
  echo "packaging release binary using version '$version'"
else
  version="$version-dev"
  echo "packaging non-release binary using version '$version'"
fi

for platform in "${platforms[@]}"; do
  GOOS=${platform} GOARCH=${arch} go build -v -o target/lc-${platform}-${arch}-${version} \
    --ldflags "-X stash0.eng.lancope.local/dev-infrastructure/project-lifecycle/helpers.version=$version \
    -X stash0.eng.lancope.local/dev-infrastructure/project-lifecycle/helpers.build=$build" \
    ./main
done

## create a binary for blackbox tests to use
cp target/lc-linux-${arch}-${version} target/lc-blackbox
