#!/usr/bin/env bash

: ${ARTIFACTORY_SERVER:=https://artifactory1.eng.lancope.local}
: ${ARTIFACTORY_PATH:=generic-dev-infrastructure/lc}

if [ ! -f /opt/netrc ] ; then
  echo "missing /opt/netrc file for lc repo, cannot publish" >&2
  exit 1
fi

set -e

echo "starting publish all binaries found in ./target"
for path in target/*; do
  file=${f##*/}
  curl -ki --netrc-file /opt/netrc -T "$path" "$ARTIFACTORY_SERVER/$ARTIFACTORY_PATH/$file"
done
