#!/usr/bin/env bash
set -e

echo go test ./command ./helpers ./main ./template
go test ./command ./helpers ./main ./template

echo go vet ./command ./helpers ./main ./template
go vet ./command ./helpers ./main ./template
